# define networks to connect containers with each other
networks:
  bde:

services:
  app:
    build: .
    image: docker-bde
    command: sh
    tty: true
    stdin_open: true
    ports:
      - "8888:8888" # Jupyter
      - "8000:8000" # Django
    networks:
      - bde
    depends_on:
      - age
      - db
      - neo4j
    volumes:
      - "..:/shared"

  age:
    image: apache/age
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: postgresDB
    networks:
      - bde
    volumes:
      - ./dbs/age:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    networks:
      - bde
    volumes:
      - ./dbs/postgres:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.18-community
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - bde
    volumes:
      - ./dbs/neo4j:/data:delegated